name: Build project
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          npm i
          npm run build
      - name: Build Next App for Github Pages
        uses: jhasuraj01/next-pages@main
      - name: Commit and push changes
        run: |
          git config --global user.name "jhasuraj01"
          git config --global user.email "44930179+jhasuraj01@users.noreply.github.com"
          git add -A
          git commit -m "New Build"
          git push
